general.import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[font]
size = 12.0 # Adjust this to your preferred font size

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.italic]
family = "MesloLGS NF"
style = "Italic"

[font.bold_italic]
family = "MesloLGS NF"
style = "Bold Italic"

[window]
padding = { x = 5, y = 5 }